# Generated by Django 5.2 on 2025-04-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etype', models.CharField(max_length=40)),
                ('eimage', models.ImageField(upload_to='')),
                ('eprice', models.CharField(max_length=20)),
                ('edes', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnum', models.CharField(max_length=60)),
                ('cvvnum', models.CharField(max_length=60)),
                ('edate', models.CharField(max_length=60)),
                ('userid', models.CharField(max_length=60)),
                ('etype', models.CharField(max_length=60)),
                ('eid', models.CharField(default='default_value', max_length=20)),
                ('eprice', models.CharField(max_length=60)),
                ('edes', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('Phn', models.CharField(max_length=10)),
            ],
        ),
    ]
